apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: cert-manager
spec:
  acme:
    email: chonuba@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: nginx
#         selector:
#           dnsNames:
#             - sockshop.oldyungdev.tech
#             - prometheus.oldyungdev.tech
#             - grafana.oldyungdev.tech
# #          matchLabels:
# #            name: front-end
# #            app: prometheus
# #            app: grafana  