apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sockshop-ingress
  namespace: sock-shop
spec:
  ingressClassName: nginx
  rules:
    - host: sockshop.oldyungdev.tech
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: front-end
                port:
                  number: 80
                  
    - host: prometheus.oldyungdev.tech
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: prom-graf-kube-prometheus-prometheus
                port:
                  number: 9090

    - host: grafana.oldyungdev.tech
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: prom-graf-grafana
                port:
                  number: 80
  tls:
  - hosts:
    - sockshop.oldyungdev.tech
    - grafana.oldyungdev.tech
    - prometheus.oldyungdev.tech
    secretName: tls-secret
